-- 0003: 수가표 관리 (관리자 수정 가능)
CREATE TABLE IF NOT EXISTS price_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category_key TEXT NOT NULL,
  name TEXT NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  note TEXT,
  sort INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_price_items_cat ON price_items(category_key, sort);
INSERT OR IGNORE INTO settings (key, value) VALUES ('pricing_updated', '2026-07');

INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '임플란트(보험)', 0, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '발치', 0, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치수절단', 0, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '근관치료', 0, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치관확장술', 0, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치은박리소파술', 0, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치근활택술', 0, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치은판절제술', 0, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '연1회 SC', 0, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치주 SC', 0, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치주 치료', 0, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치아 홈메우기', 0, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '영구치 레진', 0, NULL, 130);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '금속상 완전틀니(보험)', 0, NULL, 140);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '부분틀니(보험)', 0, NULL, 150);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '즉일충전', 0, NULL, 160);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', 'GI 충전', 0, NULL, 170);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '교합조정', 0, NULL, 180);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '잠간고정술', 0, NULL, 190);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '보철물재부착', 0, NULL, 200);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '브릿지 제거', 0, NULL, 210);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '지각과민처치', 0, NULL, 220);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '정기검진', 0, NULL, 230);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '턱관절치료', 0, NULL, 240);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치경부마모', 0, NULL, 250);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치은절제술', 0, NULL, 260);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '폴리싱', 0, NULL, 270);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', 'I&D', 0, NULL, 280);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('insured', '치근절제술', 0, NULL, 290);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '임플 PDRN 2회(8M,4M)', 120000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '덴티스임플란트', 900000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '오스템임플란트', 1000000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '전치부 덴티스 임플란트', 1000000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '전치부 오스템 임플란트', 1100000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '가이드 임플란트', 100000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '기본 뼈이식', 300000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '복잡 뼈이식', 600000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '커스텀 어버트먼트', 100000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '상악동(Crestal)', 600000, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '상악동(Lateral)', 1000000, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '유리치은이식술(FGG)', 300000, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '결합조직이식술(CTG)', 500000, NULL, 130);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '타치과 커스텀 어버트먼트', 100000, NULL, 140);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', '상악동 (Crestal-2개치아이상)', 800000, NULL, 150);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('implant', 'CT촬영', 150000, NULL, 160);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', 'super 골드 크라운', 1000000, '변동가능', 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', 'PT 골드 크라운', 1200000, '변동가능', 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', '지르코니아 PFZ (전치부)', 600000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', '지르코니아(구치부)', 500000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', 'PFM 크라운(도자기)', 450000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', 'prep후 임시치아 유지시(치아당)', 150000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', 'MTA', 100000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', '폰틱(zirconia)', 500000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('prosthetics', '폰틱(PFZ)', 600000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '부분 틀니', 1500000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '완전 틀니', 1700000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '오버덴쳐(임플란트 틀니)', 2000000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '로케이터,마그네틱', 350000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '오버덴쳐수리(단순의치상 및 교합조정)', 50000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '오버덴쳐수리(마그넷 재부착)', 100000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '오버덴쳐수리(마그넷교체)', 300000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '오버덴쳐수리(인공치수리)', 50000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '틀니 수리', 100000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '틀니 개상', 300000, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', '임시 틀니', 300000, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('denture', 'Wire Tempo(치아당/3M추가)', 100000, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진(소구치)', 100000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진(구치부)', 100000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '동일부위레진', 80000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '인접면 레진', 130000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진 b.pit', 80000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '치경부레진(간단)', 70000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '치경부레진(복잡)', 100000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '절단면 레진', 150000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진 전치부(1면)', 130000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진 전치부(2면)', 260000, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '아이콘레진', 170000, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '다이아스테마', 200000, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '인접면 충치+심미 (1면당)', 200000, NULL, 130);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '세라믹인레이(1면)', 300000, NULL, 140);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '세라믹인레이(2면)', 330000, NULL, 150);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '세라믹인레이(3면)', 360000, NULL, 160);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '세라믹온레이', 400000, NULL, 170);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '라미네이트', 550000, NULL, 180);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진 코어', 100000, NULL, 190);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '레진코어(Cr안할경우)', 150000, NULL, 200);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '포스트 레진 코어', 200000, NULL, 210);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '포스트+ 레진코어(Cr안할경우)', 320000, NULL, 220);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('conserve', '임플란트 hole change', 50000, NULL, 230);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', '소아 레진', 50000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', 'SS Crown', 150000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', 'Band & Loop', 250000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', 'Crown & loop', 250000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', '불소', 15000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', '스켈링', 50000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('kids', 'Nance Holding Arch', 250000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', 'Retainer(4치이하)', 200000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', 'Retainer(4치이상/치아당)', 50000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '교정 레진제거', 10000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '유지장치재부착(치아당)', 50000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '교정발치', 50000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '브라켓 제거', 10000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '교정유지장치', 350000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '이갈이 장치', 500000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '이갈이장치 월비 1만원', 10000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '교합안정장치', 500000, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '교합안정장치 월비 1만원', 10000, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('ortho', '세퍼레이터', 30000, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', 'Wire Splint(치아당)', 40000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', 'Flexible(치아당/3M추가)', 200000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '트리톤 연고', 20000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '큐탄', 30000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '큐어블럭', 30000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '착색제거', 20000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '타치과임플란트 hole', 50000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '타치과임플란트 나사조이기', 50000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '타치과 라미네이트 재부착', 70000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '프롤로주사(5회)', 350000, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '치주 PDRN(1앰플)', 70000, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '체외충격파1700(회당)', 70000, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '체외충격파2200(회당)', 100000, NULL, 130);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', 'CT(비급여)', 50000, NULL, 140);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '가이드 플러그', 50000, NULL, 150);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('etc', '필름제로테라피', 240000, NULL, 160);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '라미네이트', 550000, NULL, 10);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '보톡스(50유닛당)', 120000, NULL, 20);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '보톡스(100유닛)', 240000, NULL, 30);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '전문가미백1회', 140000, NULL, 40);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '전문가미백2회', 270000, NULL, 50);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '전문가미백3회', 380000, NULL, 60);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '실활치미백3회', 150000, NULL, 70);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '실활치미백2회', 100000, NULL, 80);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '자가미백 8회', 280000, NULL, 90);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '전문가미백(3회)+자가(4회)', 630000, NULL, 100);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '자가미백트레이', 150000, NULL, 110);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '치은미백(laser/악당/2회)', 250000, NULL, 120);
INSERT INTO price_items (category_key, name, price, note, sort) VALUES ('cosmetic', '치은성형술', 50000, NULL, 130);
